### PR TITLE
fix: make autofix command a conventional commit message

### PR DESCRIPTION
**Pull request by SimenB**
More closely matches what e.g. dependabot, greenkeeper, renovate etc does

### CODE REVIEW

**Comment by samuelmeuli** [comment]
Thanks for the PR!

You're right, people might prefer a different style of commit messages. I'd rather use the current style in my projects, though.

Maybe the message should be made configurable? That's how the tools you mention seem to solve this ([Dependabot config](https://dependabot.com/docs/config-file/#commit_message), [Greenkeeper config](https://greenkeeper.io/docs.html#custom-commit-messages)).

**Comment by samuelmeuli** [comment]
This could be either a `conventional_commit_message: true` option, or it could be made fully configurable (like Greenkeeper's options):

```yml
- name: Run linters
  uses: samuelmeuli/lint-action@v0.4
  with:
    github_token: ${{ secrets.github_token }}
    commit_message: "chore: fix code style issues with ${linter}",
```

**Comment by SimenB** [comment]
I think it should be the default, but making it configurable makes sense to me 👍 I won't have the time to implement it though

**Comment by samuelmeuli** [comment]
I'll implement this then.

Still, I don't think it should be the default, because Git and GitHub use the current message style:

- `Merge branch 'branch-name'`
- `Revert "commit-message"`
- `Merge pull request #1 from user/branch`

**Comment by samuelmeuli** [comment]
Released in [v0.5.0](https://github.com/samuelmeuli/lint-action/releases/tag/v0.5.0)

**Comment by SimenB** [comment]
Thanks!

**Pull request closed without merging**
